// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_first_kill = "CgkI0qK3jcESEAIQAw"; // <GPGSID>
        public const string achievement_enemy_bane = "CgkI0qK3jcESEAIQCA"; // <GPGSID>
        public const string achievement_welcome = "CgkI0qK3jcESEAIQAg"; // <GPGSID>
        public const string achievement_mediocre_destroyer = "CgkI0qK3jcESEAIQBA"; // <GPGSID>
        public const string leaderboard_score_in_five_minutes = "CgkI0qK3jcESEAIQAQ"; // <GPGSID>
        public const string achievement_fort_assault = "CgkI0qK3jcESEAIQBQ"; // <GPGSID>
        public const string leaderboard_infinite_time = "CgkI0qK3jcESEAIQCw"; // <GPGSID>
        public const string leaderboard_score_in_ten_minutes = "CgkI0qK3jcESEAIQCg"; // <GPGSID>
        public const string achievement_fort_obliterator = "CgkI0qK3jcESEAIQBg"; // <GPGSID>
        public const string achievement_fort_genocide = "CgkI0qK3jcESEAIQCQ"; // <GPGSID>
        public const string achievement_mass_controller = "CgkI0qK3jcESEAIQBw"; // <GPGSID>

}

